#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise3Solution.Resource", IsApplication=true)]

namespace Exercise3Solution
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int black = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int blue = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int orange = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int pink = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int result_backgound = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int white = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050013
			public const int button_height = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int button_margin_top = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int edt_height = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int footer_margin_bottom = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int input_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int input_text_size = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int login_button_text_size = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int login_content_margin = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int login_text_size = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int login_title_text_size = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int margin_left = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int normal_size = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int or_margin = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int password_margin_top = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int result_margin_right = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int result_text = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int title_size = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int title_text_size = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int toolbar_navigation_text_size = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int username_margin_top = 2131034125;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cinema = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int password32px = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int username32px = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int wallaper = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060011
			public const int Inverse = 2131099665;
			
			// aapt resource value: 0x7f060028
			public const int _username = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int a = 2131099685;
			
			// aapt resource value: 0x7f060020
			public const int add = 2131099680;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060026
			public const int b = 2131099686;
			
			// aapt resource value: 0x7f060002
			public const int back = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int backspace = 2131099649;
			
			// aapt resource value: 0x7f060027
			public const int c = 2131099687;
			
			// aapt resource value: 0x7f060021
			public const int change_status = 2131099681;
			
			// aapt resource value: 0x7f060013
			public const int clear = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int clear_entry = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int confirm_password = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int connect_with_facebook = 2131099652;
			
			// aapt resource value: 0x7f060014
			public const int divide = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int email_address = 2131099655;
			
			// aapt resource value: 0x7f060023
			public const int equal = 2131099683;
			
			// aapt resource value: 0x7f060005
			public const int first_name = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int i_agree_to_the = 2131099659;
			
			// aapt resource value: 0x7f06002a
			public const int interac_with_your_demons = 2131099690;
			
			// aapt resource value: 0x7f060006
			public const int last_name = 2131099654;
			
			// aapt resource value: 0x7f060029
			public const int moviens = 2131099689;
			
			// aapt resource value: 0x7f060018
			public const int mul = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int number_0 = 2131099661;
			
			// aapt resource value: 0x7f06001d
			public const int number_1 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int number_2 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int number_3 = 2131099679;
			
			// aapt resource value: 0x7f060019
			public const int number_4 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int number_5 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int number_6 = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int number_7 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int number_8 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int number_9 = 2131099671;
			
			// aapt resource value: 0x7f06002c
			public const int or = 2131099692;
			
			// aapt resource value: 0x7f060009
			public const int password = 2131099657;
			
			// aapt resource value: 0x7f060022
			public const int point = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int quadratic_equation_solver = 2131099684;
			
			// aapt resource value: 0x7f060010
			public const int quare = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int remainder = 2131099662;
			
			// aapt resource value: 0x7f06002b
			public const int sign_in = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int sign_in_with_facebook = 2131099693;
			
			// aapt resource value: 0x7f060003
			public const int sign_up = 2131099651;
			
			// aapt resource value: 0x7f06002e
			public const int signup = 2131099694;
			
			// aapt resource value: 0x7f06000f
			public const int square_root = 2131099663;
			
			// aapt resource value: 0x7f06001c
			public const int sub = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int terms_of_service = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int username = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
