#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise11.Resource", IsApplication=true)]

namespace Exercise11
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int background = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int black = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int normal_color = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int red = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int seekbar_text_color = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int linear_margin = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int seekbar_margin_right = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int seekbar_margin_top = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int seekbar_text_size = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int text_size = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int filled_circle_40 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int minus40 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int plus40 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int seek_circle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int slider_progress = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int btnDes = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int btnInc = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btnUpdate = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int customSb = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int seekbar = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int tv1 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int tvValue = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_seek_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int current_value = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int default_value = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int update = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int value = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
