#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise6And7.Resource", IsApplication=true)]

namespace Exercise6And7
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int black = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int blue = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int orange = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int pink = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int red = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int result_backgound = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int white = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050013
			public const int button_height = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int button_margin_top = 2131034127;
			
			// aapt resource value: 0x7f05001c
			public const int button_width = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int content_margin = 2131034133;
			
			// aapt resource value: 0x7f05001d
			public const int devider_margin = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int edittext_height = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int edittext_margin_left = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int edt_height = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int footer_margin_bottom = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int input_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int input_text_size = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int login_button_text_size = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int login_content_margin = 2131034122;
			
			// aapt resource value: 0x7f05001a
			public const int login_linear_margin = 2131034138;
			
			// aapt resource value: 0x7f05000c
			public const int login_text_size = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int login_title_text_size = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int margin_left = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int normal_size = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int or_margin = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int password_margin_top = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int require_margin_left = 2131034136;
			
			// aapt resource value: 0x7f050006
			public const int result_margin_right = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int result_text = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int section_title_margin_bottom = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int section_title_margin_top = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int section_title_size = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int title_size = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int title_text_size = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int toolbar_navigation_text_size = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int username_margin_top = 2131034125;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_splash = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_pink = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int code32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int customer32 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int key32_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int phone32_2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int wallaper = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int btnLogin = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int btnRegister = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int tv1 = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int login = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int mobile_number = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int name = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int no_account = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int password = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int referee_code = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int register = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SplashTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
