#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise1Solution.Resource", IsApplication=true)]

namespace Exercise1Solution
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int pink = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int edt_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int margin_left = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int normal_size = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int title_size = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int toolbar_navigation_text_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logofb = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tv1 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int back = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int backspace = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int confirm_password = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int connect_with_facebook = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int email_address = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int first_name = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int i_agree_to_the = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int last_name = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int password = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int sign_up = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int terms_of_service = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int username = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
